//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  portfolioFeatureWalls: PortfolioFeatureWalls;
  portfolioFeatureWallsConnection: PortfolioFeatureWallsConnection;
  portfolioClosets: PortfolioClosets;
  portfolioClosetsConnection: PortfolioClosetsConnection;
  portfolioMediaWalls: PortfolioMediaWalls;
  portfolioMediaWallsConnection: PortfolioMediaWallsConnection;
  portfolioHallways: PortfolioHallways;
  portfolioHallwaysConnection: PortfolioHallwaysConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPortfolioFeatureWallsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPortfolioFeatureWallsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PortfolioFeatureWallsFilter>;
};


export type QueryPortfolioClosetsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPortfolioClosetsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PortfolioClosetsFilter>;
};


export type QueryPortfolioMediaWallsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPortfolioMediaWallsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PortfolioMediaWallsFilter>;
};


export type QueryPortfolioHallwaysArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPortfolioHallwaysConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PortfolioHallwaysFilter>;
};

export type DocumentFilter = {
  portfolioFeatureWalls?: InputMaybe<PortfolioFeatureWallsFilter>;
  portfolioClosets?: InputMaybe<PortfolioClosetsFilter>;
  portfolioMediaWalls?: InputMaybe<PortfolioMediaWallsFilter>;
  portfolioHallways?: InputMaybe<PortfolioHallwaysFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = PortfolioFeatureWalls | PortfolioClosets | PortfolioMediaWalls | PortfolioHallways | Folder;

export type PortfolioFeatureWallsItems = {
  __typename?: 'PortfolioFeatureWallsItems';
  label?: Maybe<Scalars['String']['output']>;
  src?: Maybe<Scalars['String']['output']>;
};

export type PortfolioFeatureWalls = Node & Document & {
  __typename?: 'PortfolioFeatureWalls';
  heading?: Maybe<Scalars['String']['output']>;
  items?: Maybe<Array<Maybe<PortfolioFeatureWallsItems>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type PortfolioFeatureWallsItemsFilter = {
  label?: InputMaybe<StringFilter>;
  src?: InputMaybe<ImageFilter>;
};

export type PortfolioFeatureWallsFilter = {
  heading?: InputMaybe<StringFilter>;
  items?: InputMaybe<PortfolioFeatureWallsItemsFilter>;
};

export type PortfolioFeatureWallsConnectionEdges = {
  __typename?: 'PortfolioFeatureWallsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<PortfolioFeatureWalls>;
};

export type PortfolioFeatureWallsConnection = Connection & {
  __typename?: 'PortfolioFeatureWallsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PortfolioFeatureWallsConnectionEdges>>>;
};

export type PortfolioClosetsItems = {
  __typename?: 'PortfolioClosetsItems';
  label?: Maybe<Scalars['String']['output']>;
  src?: Maybe<Scalars['String']['output']>;
};

export type PortfolioClosets = Node & Document & {
  __typename?: 'PortfolioClosets';
  heading?: Maybe<Scalars['String']['output']>;
  items?: Maybe<Array<Maybe<PortfolioClosetsItems>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PortfolioClosetsItemsFilter = {
  label?: InputMaybe<StringFilter>;
  src?: InputMaybe<ImageFilter>;
};

export type PortfolioClosetsFilter = {
  heading?: InputMaybe<StringFilter>;
  items?: InputMaybe<PortfolioClosetsItemsFilter>;
};

export type PortfolioClosetsConnectionEdges = {
  __typename?: 'PortfolioClosetsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<PortfolioClosets>;
};

export type PortfolioClosetsConnection = Connection & {
  __typename?: 'PortfolioClosetsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PortfolioClosetsConnectionEdges>>>;
};

export type PortfolioMediaWallsItems = {
  __typename?: 'PortfolioMediaWallsItems';
  label?: Maybe<Scalars['String']['output']>;
  src?: Maybe<Scalars['String']['output']>;
};

export type PortfolioMediaWalls = Node & Document & {
  __typename?: 'PortfolioMediaWalls';
  heading?: Maybe<Scalars['String']['output']>;
  items?: Maybe<Array<Maybe<PortfolioMediaWallsItems>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PortfolioMediaWallsItemsFilter = {
  label?: InputMaybe<StringFilter>;
  src?: InputMaybe<ImageFilter>;
};

export type PortfolioMediaWallsFilter = {
  heading?: InputMaybe<StringFilter>;
  items?: InputMaybe<PortfolioMediaWallsItemsFilter>;
};

export type PortfolioMediaWallsConnectionEdges = {
  __typename?: 'PortfolioMediaWallsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<PortfolioMediaWalls>;
};

export type PortfolioMediaWallsConnection = Connection & {
  __typename?: 'PortfolioMediaWallsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PortfolioMediaWallsConnectionEdges>>>;
};

export type PortfolioHallwaysItems = {
  __typename?: 'PortfolioHallwaysItems';
  label?: Maybe<Scalars['String']['output']>;
  src?: Maybe<Scalars['String']['output']>;
};

export type PortfolioHallways = Node & Document & {
  __typename?: 'PortfolioHallways';
  heading?: Maybe<Scalars['String']['output']>;
  items?: Maybe<Array<Maybe<PortfolioHallwaysItems>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PortfolioHallwaysItemsFilter = {
  label?: InputMaybe<StringFilter>;
  src?: InputMaybe<ImageFilter>;
};

export type PortfolioHallwaysFilter = {
  heading?: InputMaybe<StringFilter>;
  items?: InputMaybe<PortfolioHallwaysItemsFilter>;
};

export type PortfolioHallwaysConnectionEdges = {
  __typename?: 'PortfolioHallwaysConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<PortfolioHallways>;
};

export type PortfolioHallwaysConnection = Connection & {
  __typename?: 'PortfolioHallwaysConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PortfolioHallwaysConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updatePortfolioFeatureWalls: PortfolioFeatureWalls;
  createPortfolioFeatureWalls: PortfolioFeatureWalls;
  updatePortfolioClosets: PortfolioClosets;
  createPortfolioClosets: PortfolioClosets;
  updatePortfolioMediaWalls: PortfolioMediaWalls;
  createPortfolioMediaWalls: PortfolioMediaWalls;
  updatePortfolioHallways: PortfolioHallways;
  createPortfolioHallways: PortfolioHallways;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdatePortfolioFeatureWallsArgs = {
  relativePath: Scalars['String']['input'];
  params: PortfolioFeatureWallsMutation;
};


export type MutationCreatePortfolioFeatureWallsArgs = {
  relativePath: Scalars['String']['input'];
  params: PortfolioFeatureWallsMutation;
};


export type MutationUpdatePortfolioClosetsArgs = {
  relativePath: Scalars['String']['input'];
  params: PortfolioClosetsMutation;
};


export type MutationCreatePortfolioClosetsArgs = {
  relativePath: Scalars['String']['input'];
  params: PortfolioClosetsMutation;
};


export type MutationUpdatePortfolioMediaWallsArgs = {
  relativePath: Scalars['String']['input'];
  params: PortfolioMediaWallsMutation;
};


export type MutationCreatePortfolioMediaWallsArgs = {
  relativePath: Scalars['String']['input'];
  params: PortfolioMediaWallsMutation;
};


export type MutationUpdatePortfolioHallwaysArgs = {
  relativePath: Scalars['String']['input'];
  params: PortfolioHallwaysMutation;
};


export type MutationCreatePortfolioHallwaysArgs = {
  relativePath: Scalars['String']['input'];
  params: PortfolioHallwaysMutation;
};

export type DocumentUpdateMutation = {
  portfolioFeatureWalls?: InputMaybe<PortfolioFeatureWallsMutation>;
  portfolioClosets?: InputMaybe<PortfolioClosetsMutation>;
  portfolioMediaWalls?: InputMaybe<PortfolioMediaWallsMutation>;
  portfolioHallways?: InputMaybe<PortfolioHallwaysMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  portfolioFeatureWalls?: InputMaybe<PortfolioFeatureWallsMutation>;
  portfolioClosets?: InputMaybe<PortfolioClosetsMutation>;
  portfolioMediaWalls?: InputMaybe<PortfolioMediaWallsMutation>;
  portfolioHallways?: InputMaybe<PortfolioHallwaysMutation>;
};

export type PortfolioFeatureWallsItemsMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  src?: InputMaybe<Scalars['String']['input']>;
};

export type PortfolioFeatureWallsMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  items?: InputMaybe<Array<InputMaybe<PortfolioFeatureWallsItemsMutation>>>;
};

export type PortfolioClosetsItemsMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  src?: InputMaybe<Scalars['String']['input']>;
};

export type PortfolioClosetsMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  items?: InputMaybe<Array<InputMaybe<PortfolioClosetsItemsMutation>>>;
};

export type PortfolioMediaWallsItemsMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  src?: InputMaybe<Scalars['String']['input']>;
};

export type PortfolioMediaWallsMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  items?: InputMaybe<Array<InputMaybe<PortfolioMediaWallsItemsMutation>>>;
};

export type PortfolioHallwaysItemsMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  src?: InputMaybe<Scalars['String']['input']>;
};

export type PortfolioHallwaysMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  items?: InputMaybe<Array<InputMaybe<PortfolioHallwaysItemsMutation>>>;
};

export type PortfolioFeatureWallsPartsFragment = { __typename: 'PortfolioFeatureWalls', heading?: string | null, items?: Array<{ __typename: 'PortfolioFeatureWallsItems', label?: string | null, src?: string | null } | null> | null };

export type PortfolioClosetsPartsFragment = { __typename: 'PortfolioClosets', heading?: string | null, items?: Array<{ __typename: 'PortfolioClosetsItems', label?: string | null, src?: string | null } | null> | null };

export type PortfolioMediaWallsPartsFragment = { __typename: 'PortfolioMediaWalls', heading?: string | null, items?: Array<{ __typename: 'PortfolioMediaWallsItems', label?: string | null, src?: string | null } | null> | null };

export type PortfolioHallwaysPartsFragment = { __typename: 'PortfolioHallways', heading?: string | null, items?: Array<{ __typename: 'PortfolioHallwaysItems', label?: string | null, src?: string | null } | null> | null };

export type PortfolioFeatureWallsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PortfolioFeatureWallsQuery = { __typename?: 'Query', portfolioFeatureWalls: { __typename: 'PortfolioFeatureWalls', id: string, heading?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'PortfolioFeatureWallsItems', label?: string | null, src?: string | null } | null> | null } };

export type PortfolioFeatureWallsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PortfolioFeatureWallsFilter>;
}>;


export type PortfolioFeatureWallsConnectionQuery = { __typename?: 'Query', portfolioFeatureWallsConnection: { __typename?: 'PortfolioFeatureWallsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PortfolioFeatureWallsConnectionEdges', cursor: string, node?: { __typename: 'PortfolioFeatureWalls', id: string, heading?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'PortfolioFeatureWallsItems', label?: string | null, src?: string | null } | null> | null } | null } | null> | null } };

export type PortfolioClosetsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PortfolioClosetsQuery = { __typename?: 'Query', portfolioClosets: { __typename: 'PortfolioClosets', id: string, heading?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'PortfolioClosetsItems', label?: string | null, src?: string | null } | null> | null } };

export type PortfolioClosetsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PortfolioClosetsFilter>;
}>;


export type PortfolioClosetsConnectionQuery = { __typename?: 'Query', portfolioClosetsConnection: { __typename?: 'PortfolioClosetsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PortfolioClosetsConnectionEdges', cursor: string, node?: { __typename: 'PortfolioClosets', id: string, heading?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'PortfolioClosetsItems', label?: string | null, src?: string | null } | null> | null } | null } | null> | null } };

export type PortfolioMediaWallsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PortfolioMediaWallsQuery = { __typename?: 'Query', portfolioMediaWalls: { __typename: 'PortfolioMediaWalls', id: string, heading?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'PortfolioMediaWallsItems', label?: string | null, src?: string | null } | null> | null } };

export type PortfolioMediaWallsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PortfolioMediaWallsFilter>;
}>;


export type PortfolioMediaWallsConnectionQuery = { __typename?: 'Query', portfolioMediaWallsConnection: { __typename?: 'PortfolioMediaWallsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PortfolioMediaWallsConnectionEdges', cursor: string, node?: { __typename: 'PortfolioMediaWalls', id: string, heading?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'PortfolioMediaWallsItems', label?: string | null, src?: string | null } | null> | null } | null } | null> | null } };

export type PortfolioHallwaysQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PortfolioHallwaysQuery = { __typename?: 'Query', portfolioHallways: { __typename: 'PortfolioHallways', id: string, heading?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'PortfolioHallwaysItems', label?: string | null, src?: string | null } | null> | null } };

export type PortfolioHallwaysConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PortfolioHallwaysFilter>;
}>;


export type PortfolioHallwaysConnectionQuery = { __typename?: 'Query', portfolioHallwaysConnection: { __typename?: 'PortfolioHallwaysConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PortfolioHallwaysConnectionEdges', cursor: string, node?: { __typename: 'PortfolioHallways', id: string, heading?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'PortfolioHallwaysItems', label?: string | null, src?: string | null } | null> | null } | null } | null> | null } };

export const PortfolioFeatureWallsPartsFragmentDoc = gql`
    fragment PortfolioFeatureWallsParts on PortfolioFeatureWalls {
  __typename
  heading
  items {
    __typename
    label
    src
  }
}
    `;
export const PortfolioClosetsPartsFragmentDoc = gql`
    fragment PortfolioClosetsParts on PortfolioClosets {
  __typename
  heading
  items {
    __typename
    label
    src
  }
}
    `;
export const PortfolioMediaWallsPartsFragmentDoc = gql`
    fragment PortfolioMediaWallsParts on PortfolioMediaWalls {
  __typename
  heading
  items {
    __typename
    label
    src
  }
}
    `;
export const PortfolioHallwaysPartsFragmentDoc = gql`
    fragment PortfolioHallwaysParts on PortfolioHallways {
  __typename
  heading
  items {
    __typename
    label
    src
  }
}
    `;
export const PortfolioFeatureWallsDocument = gql`
    query portfolioFeatureWalls($relativePath: String!) {
  portfolioFeatureWalls(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PortfolioFeatureWallsParts
  }
}
    ${PortfolioFeatureWallsPartsFragmentDoc}`;
export const PortfolioFeatureWallsConnectionDocument = gql`
    query portfolioFeatureWallsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PortfolioFeatureWallsFilter) {
  portfolioFeatureWallsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PortfolioFeatureWallsParts
      }
    }
  }
}
    ${PortfolioFeatureWallsPartsFragmentDoc}`;
export const PortfolioClosetsDocument = gql`
    query portfolioClosets($relativePath: String!) {
  portfolioClosets(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PortfolioClosetsParts
  }
}
    ${PortfolioClosetsPartsFragmentDoc}`;
export const PortfolioClosetsConnectionDocument = gql`
    query portfolioClosetsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PortfolioClosetsFilter) {
  portfolioClosetsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PortfolioClosetsParts
      }
    }
  }
}
    ${PortfolioClosetsPartsFragmentDoc}`;
export const PortfolioMediaWallsDocument = gql`
    query portfolioMediaWalls($relativePath: String!) {
  portfolioMediaWalls(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PortfolioMediaWallsParts
  }
}
    ${PortfolioMediaWallsPartsFragmentDoc}`;
export const PortfolioMediaWallsConnectionDocument = gql`
    query portfolioMediaWallsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PortfolioMediaWallsFilter) {
  portfolioMediaWallsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PortfolioMediaWallsParts
      }
    }
  }
}
    ${PortfolioMediaWallsPartsFragmentDoc}`;
export const PortfolioHallwaysDocument = gql`
    query portfolioHallways($relativePath: String!) {
  portfolioHallways(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PortfolioHallwaysParts
  }
}
    ${PortfolioHallwaysPartsFragmentDoc}`;
export const PortfolioHallwaysConnectionDocument = gql`
    query portfolioHallwaysConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PortfolioHallwaysFilter) {
  portfolioHallwaysConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PortfolioHallwaysParts
      }
    }
  }
}
    ${PortfolioHallwaysPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      portfolioFeatureWalls(variables: PortfolioFeatureWallsQueryVariables, options?: C): Promise<{data: PortfolioFeatureWallsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PortfolioFeatureWallsQueryVariables, query: string}> {
        return requester<{data: PortfolioFeatureWallsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PortfolioFeatureWallsQueryVariables, query: string}, PortfolioFeatureWallsQueryVariables>(PortfolioFeatureWallsDocument, variables, options);
      },
    portfolioFeatureWallsConnection(variables?: PortfolioFeatureWallsConnectionQueryVariables, options?: C): Promise<{data: PortfolioFeatureWallsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PortfolioFeatureWallsConnectionQueryVariables, query: string}> {
        return requester<{data: PortfolioFeatureWallsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PortfolioFeatureWallsConnectionQueryVariables, query: string}, PortfolioFeatureWallsConnectionQueryVariables>(PortfolioFeatureWallsConnectionDocument, variables, options);
      },
    portfolioClosets(variables: PortfolioClosetsQueryVariables, options?: C): Promise<{data: PortfolioClosetsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PortfolioClosetsQueryVariables, query: string}> {
        return requester<{data: PortfolioClosetsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PortfolioClosetsQueryVariables, query: string}, PortfolioClosetsQueryVariables>(PortfolioClosetsDocument, variables, options);
      },
    portfolioClosetsConnection(variables?: PortfolioClosetsConnectionQueryVariables, options?: C): Promise<{data: PortfolioClosetsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PortfolioClosetsConnectionQueryVariables, query: string}> {
        return requester<{data: PortfolioClosetsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PortfolioClosetsConnectionQueryVariables, query: string}, PortfolioClosetsConnectionQueryVariables>(PortfolioClosetsConnectionDocument, variables, options);
      },
    portfolioMediaWalls(variables: PortfolioMediaWallsQueryVariables, options?: C): Promise<{data: PortfolioMediaWallsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PortfolioMediaWallsQueryVariables, query: string}> {
        return requester<{data: PortfolioMediaWallsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PortfolioMediaWallsQueryVariables, query: string}, PortfolioMediaWallsQueryVariables>(PortfolioMediaWallsDocument, variables, options);
      },
    portfolioMediaWallsConnection(variables?: PortfolioMediaWallsConnectionQueryVariables, options?: C): Promise<{data: PortfolioMediaWallsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PortfolioMediaWallsConnectionQueryVariables, query: string}> {
        return requester<{data: PortfolioMediaWallsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PortfolioMediaWallsConnectionQueryVariables, query: string}, PortfolioMediaWallsConnectionQueryVariables>(PortfolioMediaWallsConnectionDocument, variables, options);
      },
    portfolioHallways(variables: PortfolioHallwaysQueryVariables, options?: C): Promise<{data: PortfolioHallwaysQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PortfolioHallwaysQueryVariables, query: string}> {
        return requester<{data: PortfolioHallwaysQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PortfolioHallwaysQueryVariables, query: string}, PortfolioHallwaysQueryVariables>(PortfolioHallwaysDocument, variables, options);
      },
    portfolioHallwaysConnection(variables?: PortfolioHallwaysConnectionQueryVariables, options?: C): Promise<{data: PortfolioHallwaysConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PortfolioHallwaysConnectionQueryVariables, query: string}> {
        return requester<{data: PortfolioHallwaysConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PortfolioHallwaysConnectionQueryVariables, query: string}, PortfolioHallwaysConnectionQueryVariables>(PortfolioHallwaysConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  